wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.15.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691111354.758621
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.11.1
      5: 0.15.5
      8:
      - 5
