wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.2
    cli_version: 0.15.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690266539.329899
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.6.2
      5: 0.15.6
      8:
      - 3
      - 5
